# Generated by Django 3.2.16 on 2022-12-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221206_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user_pk',
        ),
    ]
